---
# Prettier Configuration (https://prettier.io/docs/en/options.html)

printWidth: 100        # Line length where Prettier will try wrap
tabWidth: 2            # Number of spaces per indentation level
useTabs: false         # Use spaces instead of tabs
semi: true             # Add semicolons at the end of statements
singleQuote: true      # Use single quotes instead of double quotes
quoteProps: "as-needed" # Only add quotes around object properties when needed
jsxSingleQuote: false  # Use double quotes in JSX
trailingComma: "es5"   # Add trailing commas where valid in ES5
bracketSpacing: true   # Print spaces between brackets in object literals
bracketSameLine: false # Put the > of a multi-line HTML element at the end of the last line
arrowParens: "always"  # Include parentheses around a sole arrow function parameter
proseWrap: "preserve"  # Don't change wrapping in markdown files
htmlWhitespaceSensitivity: "css" # HTML whitespace handling
endOfLine: "lf"        # Line endings (LF for cross-platform compatibility)
embeddedLanguageFormatting: "auto" # Format embedded code
